table 'Current Active Memberships - Active Accounts'
	lineageTag: 6c6b176a-feb2-4d31-a60c-db4a6d45167a

	column Attribute
		dataType: string
		lineageTag: 45a97a7b-6f6f-4f00-8bad-8b11dfb850db
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 928b1d6d-560e-4ccb-a032-354face04387
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Current Active Memberships - Active Accounts' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Trainings\City of Frisco Power Bi\Datasets\Current Active Memberships - Active Accounts.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Contact ID", "First Name", "Last Name", "Activation DateTime", "Expiry Date", "Residency", "Age", "Name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Price", type number}}),
				    #"Pivoted Column" = Table.Pivot(#"Changed Type", List.Distinct(#"Changed Type"[Gender]), "Gender", "Price", List.Sum),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Pivoted Column", {}, "Attribute", "Value")
				in
				    #"Unpivoted Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

