table 'Floor Attendance'
	lineageTag: ec888f29-3fd9-4fa1-a282-e2c60ee838da

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 410e9cb1-0171-4f50-8cc3-239ae6134928
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Start time'
		dataType: dateTime
		formatString: General Date
		lineageTag: df24b1ca-4c61-454b-9352-8bf8e80594ed
		summarizeBy: none
		sourceColumn: Start time

		variation Variation
			isDefault
			relationship: a0483a3d-135c-42cc-8dda-02dc24363eea
			defaultHierarchy: LocalDateTable_3f5c8b45-98ac-4f9e-b529-c0ac88d5b420.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Completion time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 85d4fb14-9652-4573-87a8-4fef1e27c307
		summarizeBy: none
		sourceColumn: Completion time

		variation Variation
			isDefault
			relationship: 5fad42d7-06b9-4258-82dd-0354f9105686
			defaultHierarchy: LocalDateTable_c931c697-e5fe-4273-b03e-029514369982.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: a43cb523-5189-4d8f-b3d4-1d2e1d69a2f2
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 8d63a456-588c-42d4-8f36-692eee421235
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: string
		lineageTag: e634c219-6ddc-4753-bcf3-51a9d16960db
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ab614f48-35c6-47e7-addf-4bd89b0bee2f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: d6004486-8125-405b-809f-9de87d0cca18
			defaultHierarchy: LocalDateTable_fb359586-0eed-46bb-8abf-f48f542b6dd0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 594bbafb-5222-4168-a4bd-41f6a8248d0e
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Pickleball
		dataType: int64
		formatString: 0
		lineageTag: cb2618e8-05f5-4e0c-8adc-c2e454308dd8
		summarizeBy: sum
		sourceColumn: Pickleball

		annotation SummarizationSetBy = Automatic

	column Precor
		dataType: int64
		formatString: 0
		lineageTag: e22f945e-f8bb-4e8c-9742-683322ee6638
		summarizeBy: sum
		sourceColumn: Precor

		annotation SummarizationSetBy = Automatic

	column 'LF Cardio'
		dataType: double
		lineageTag: 166d9ba1-6137-4eb6-add3-3d43727d8282
		summarizeBy: sum
		sourceColumn: LF Cardio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Queenax
		dataType: int64
		formatString: 0
		lineageTag: 6b95ca50-e473-43c1-b472-b32045731ca8
		summarizeBy: sum
		sourceColumn: Queenax

		annotation SummarizationSetBy = Automatic

	column 'Fitness Floor'
		dataType: int64
		formatString: 0
		lineageTag: e77b93e3-a597-441b-bb70-d58890a245d4
		summarizeBy: sum
		sourceColumn: Fitness Floor

		annotation SummarizationSetBy = Automatic

	column 'Free Weights'
		dataType: int64
		formatString: 0
		lineageTag: a1a235f6-e7e8-4196-9af2-24bae02a326f
		summarizeBy: sum
		sourceColumn: Free Weights

		annotation SummarizationSetBy = Automatic

	column Studios
		dataType: int64
		formatString: 0
		lineageTag: ceb5e8f9-223f-4170-a9d5-2fe625235c66
		summarizeBy: sum
		sourceColumn: Studios

		annotation SummarizationSetBy = Automatic

	column 'Gold Medal'
		dataType: int64
		formatString: 0
		lineageTag: d0fed82e-b07e-49e0-b8a3-0d135c8aeae7
		summarizeBy: sum
		sourceColumn: Gold Medal

		annotation SummarizationSetBy = Automatic

	partition 'Floor Attendance' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Trainings\City of Frisco Power Bi\Datasets\Fitness Floor Attendance Input March 2025 - Current(1-564).xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"ID", Int64.Type}, {"Start time", type datetime}, {"Completion time", type datetime}, {"Email", type text}, {"Name", type any}, {"Day", type text}, {"Date", type date}, {"Time", type time}, {"Pickleball", Int64.Type}, {"Precor", Int64.Type}, {"LF Cardio", type number}, {"Queenax", Int64.Type}, {"Fitness Floor", Int64.Type}, {"Free Weights", Int64.Type}, {"Studios", Int64.Type}, {"Gold Medal", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

